version: '3.9'
services:
  web:
    build:
     context: ./web
     dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/web

    links:
      - flask_db
  queue:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - flask_db

  flask_db:
     image: mysql:5.7.22
     container_name: flask_db
     restart: always
     environment:
       MYSQL_DATABASE: web
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - .dbdata:/var/lib/mysql
     ports:
       - "33067:3306"
